# Generated by Django 4.2.1 on 2023-05-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_appuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_holding_datetime_start', models.DateTimeField()),
                ('lesson_holding_datetime_end', models.DateTimeField()),
                ('homework', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_material_text', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_material_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('discipline_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.disciplineteacher')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classcode')),
            ],
            options={
                'permissions': (('can_view_student_journal', 'Can view student journal'), ('can_view_class_journal', 'Can view class journal'), ('can_give_homework', 'Can give homework to class')),
                'unique_together': {('lesson_holding_datetime_start', 'student_class'), ('lesson_holding_datetime_start', 'discipline_teacher')},
            },
        ),
    ]
