# Generated by Django 4.2 on 2023-05-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classcode'),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='discipline_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.disciplineteacher'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together={('lesson_holding_datetime_start', 'discipline_teacher'), ('lesson_holding_datetime_start', 'class_code'), ('lesson_holding_datetime_start', 'sequence_num')},
        ),
    ]
