# Generated by Django 4.2 on 2023-05-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='discipline_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.disciplineteacher'),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classcode'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together={('lesson_holding_datetime', 'student_class'), ('lesson_holding_datetime', 'discipline_teacher')},
        ),
    ]
