# Generated by Django 4.2.1 on 2023-05-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_appuser_age'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonschedule',
            old_name='student_class',
            new_name='class_code',
        ),
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together={('lesson_holding_datetime_start', 'discipline_teacher'), ('lesson_holding_datetime_start', 'class_code')},
        ),
    ]
