# Generated by Django 2.2.28 on 2023-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20230519_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonschedule',
            name='lesson_material_file_path',
        ),
        migrations.RemoveField(
            model_name='lessonschedule',
            name='lesson_material_text',
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='lesson_material_file',
            field=models.FileField(blank=True, null=True, upload_to='materials'),
        ),
    ]
