# Generated by Django 2.2.28 on 2023-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('scheduling', '0002_auto_20230513_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='sequence_num',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together={('lesson_holding_datetime_start', 'class_code'), ('lesson_holding_datetime_start', 'discipline_teacher'), ('lesson_holding_datetime_start', 'sequence_num')},
        ),
    ]
