# Generated by Django 2.2.28 on 2023-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_auto_20230520_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='term_num',
            field=models.SmallIntegerField(default=4),
            preserve_default=False,
        ),
    ]
