# Generated by Django 2.2.28 on 2023-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_lessonschedule_term_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='classroom',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
