# Generated by Django 2.2.28 on 2023-05-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230522_2056'),
        ('scheduling', '0006_auto_20230523_1813'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together={('lesson_holding_datetime_start', 'discipline_teacher'), ('lesson_holding_datetime_start', 'class_code'), ('lesson_holding_datetime_start', 'classroom')},
        ),
    ]
