# Generated by Django 2.2.28 on 2023-05-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcode',
            name='class_code',
            field=models.CharField(max_length=3),
        ),
    ]
