# Generated by Django 4.2 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcode',
            options={},
        ),
        migrations.AlterField(
            model_name='classcode',
            name='class_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classcode',
            unique_together={('class_code', 'status')},
        ),
    ]
