# Generated by Django 2.2.28 on 2023-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230529_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classstudent',
            options={},
        ),
        migrations.CreateModel(
            name='ClassDisciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.SmallIntegerField()),
                ('studied_disciplines', models.ManyToManyField(to='users.DisciplineName')),
            ],
        ),
    ]
