# Generated by Django 4.2 on 2023-05-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_classcode_options_alter_classcode_class_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classcode',
            unique_together=set(),
        ),
    ]
