# Generated by Django 2.2.28 on 2023-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230529_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdisciplines',
            name='class_num',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='classdisciplines',
            name='studied_disciplines',
            field=models.ManyToManyField(blank=True, null=True, to='users.DisciplineName'),
        ),
    ]
