# Generated by Django 2.2.28 on 2023-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230529_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdisciplines',
            name='studied_disciplines',
            field=models.ManyToManyField(blank=True, to='users.DisciplineName'),
        ),
    ]
