# Generated by Django 4.2 on 2023-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_classcode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcode',
            name='class_code',
            field=models.CharField(max_length=5),
        ),
    ]
