# Generated by Django 4.2 on 2023-05-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_classcode_class_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classcode',
            unique_together={('class_code', 'status')},
        ),
    ]
