# Generated by Django 4.2 on 2023-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_classcode_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classcode',
            unique_together=set(),
        ),
    ]
