# Generated by Django 4.2.1 on 2023-05-07 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_classcode_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
