# Generated by Django 4.2.1 on 2023-05-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_appuser_age_alter_appuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
