# Generated by Django 4.2 on 2023-05-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('grades_nonattendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonattendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.lessonschedule'),
        ),
    ]
