# Generated by Django 2.2.28 on 2023-05-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades_nonattendance', '0003_lessonresults_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresults',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_to_results', to='scheduling.LessonSchedule'),
        ),
    ]
