# Generated by Django 2.2.28 on 2023-05-20 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades_nonattendance', '0004_auto_20230520_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresults',
            name='remark',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='lessonresults',
            name='grade',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='lessonresults',
            name='non_attendance_reason',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
