# Generated by Django 4.2 on 2023-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades_nonattendance', '0005_auto_20230520_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresults',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
